apiVersion: v1
kind: Secret
metadata:
  name: auth-backend-secrets
type: Opaque
data:
  MONGO_URI: <base64-encoded-mongo-uri>
  JWT_SECRET: <base64-encoded-jwt-secret>
  AWS_KEY_ID: <base64-encoded-aws-key-id>
  AWS_SECRET_KEY: <base64-encoded-aws-secret-key>
